name: Docker Image CI

on:
  push:
    tags: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
      run: |
        ls -l
        echo "Docker login"
        docker login -u $DOCKERHUB -p $DOCKERHUB_KEY
        echo "running build"
        docker build -f docker/Dockerfile -t kosaraju333/heimdall:'v0.1' .
        echo "pushing image"
        docker push kosaraju333/heimdall:'v0.1'
        echo "DONE!"
    
